# Generated by Django 3.1.3 on 2021-04-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCart', '0002_auto_20210420_2045'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='cartItems',
        ),
    ]
