# Generated by Django 3.1.3 on 2021-04-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCart', '0003_auto_20210420_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
