# Generated by Django 3.1.3 on 2021-04-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCart', '0007_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
