# Generated by Django 3.1.3 on 2021-04-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webshopRestaurant', '0006_auto_20210406_2009'),
        ('webshopCatalog', '0001_initial'),
        ('webshopCart', '0012_delete_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshopCatalog.product')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshopRestaurant.restaurant')),
            ],
            options={
                'db_table': 'cartItems',
                'ordering': ['date_added'],
            },
        ),
    ]
