# Generated by Django 3.1.3 on 2021-04-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=15)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('has_delivery', models.BooleanField(default=True)),
                ('delivery_weekdays', models.CharField(max_length=2)),
            ],
        ),
    ]
