# Generated by Django 3.1.3 on 2021-04-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=15)),
                ('is_active', models.BooleanField(default=True, help_text='If active it is possible to order takeaway both for delivery and pickup')),
                ('has_delivery', models.BooleanField(default=True, help_text='If active it is possible to order delivery. If not on, it is only possible to order pickup')),
                ('delivery_radius', models.IntegerField(help_text='Delivery radius in km')),
                ('delivery_monday_active', models.BooleanField(default=True, help_text='If active, delivery can be performed on Monday')),
                ('delivery_monday_timestart', models.TimeField()),
                ('delivery_monday_timeend', models.TimeField()),
                ('delivery_tuesday_active', models.BooleanField(default=True, help_text='If active, delivery can be performed on Tuesday')),
                ('delivery_tuesday_timestart', models.TimeField()),
                ('delivery_tuesday_timeend', models.TimeField()),
                ('delivery_wednesday_active', models.BooleanField(default=True, help_text='If active, delivery can be performed on Wednesday')),
                ('delivery_wednesday_timestart', models.TimeField()),
                ('delivery_wednesday_timeend', models.TimeField()),
                ('delivery_thursday_active', models.BooleanField(default=True, help_text='If active, delivery can be performed on Thursday')),
                ('delivery_thursday_timestart', models.TimeField()),
                ('delivery_thursday_timeend', models.TimeField()),
                ('delivery_friday_active', models.BooleanField(default=True, help_text='If active, delivery can be performed on Friday')),
                ('delivery_friday_timestart', models.TimeField()),
                ('delivery_friday_timeend', models.TimeField()),
                ('delivery_saturday_active', models.BooleanField(default=True, help_text='If active, delivery can be performed on Saturday')),
                ('delivery_saturday_timestart', models.TimeField()),
                ('delivery_saturday_timeend', models.TimeField()),
                ('delivery_sunday_active', models.BooleanField(default=True, help_text='If active, delivery can be performed on Sunday')),
                ('delivery_sunday_timestart', models.TimeField()),
                ('delivery_sunday_timeend', models.TimeField()),
                ('pickup_monday_active', models.BooleanField(default=True, help_text='If active, pickup is possible on Monday')),
                ('pickup_monday_timestart', models.TimeField()),
                ('pickup_monday_timeend', models.TimeField()),
                ('pickup_tuesday_active', models.BooleanField(default=True, help_text='If active, pickup is possible on Tuesday')),
                ('pickup_tuesday_timestart', models.TimeField()),
                ('pickup_tuesday_timeend', models.TimeField()),
                ('pickup_wednesday_active', models.BooleanField(default=True, help_text='If active, pickup is possible on Wednesday')),
                ('pickup_wednesday_timestart', models.TimeField()),
                ('pickup_wednesday_timeend', models.TimeField()),
                ('pickup_thursday_active', models.BooleanField(default=True, help_text='If active, pickup is possible on Thursday')),
                ('pickup_thursday_timestart', models.TimeField()),
                ('pickup_thursday_timeend', models.TimeField()),
                ('pickup_friday_active', models.BooleanField(default=True, help_text='If active, pickup is possible on Friday')),
                ('pickup_friday_timestart', models.TimeField()),
                ('pickup_friday_timeend', models.TimeField()),
                ('pickup_saturday_active', models.BooleanField(default=True, help_text='If active, pickup is possible on Saturday')),
                ('pickup_saturday_timestart', models.TimeField()),
                ('pickup_saturday_timeend', models.TimeField()),
                ('pickup_sunday_active', models.BooleanField(default=True, help_text='If active, pickup is possible on Sunday')),
                ('pickup_sunday_timestart', models.TimeField()),
                ('pickup_sunday_timeend', models.TimeField()),
            ],
            options={
                'db_table': 'restaurant',
                'ordering': ['-name'],
            },
        ),
    ]
