# Generated by Django 3.1.3 on 2021-04-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCatalog', '0001_initial'),
        ('webshopRestaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ManyToManyField(to='webshopCatalog.Category'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='products',
            field=models.ManyToManyField(to='webshopCatalog.Product'),
        ),
    ]
