# Generated by Django 3.1.3 on 2021-04-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopRestaurant', '0002_auto_20210405_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_preparationtime',
            field=models.PositiveSmallIntegerField(default=30, help_text='Time it takes to prepare the order. The client cannot pickup on a time earlier than the defined minutes'),
        ),
    ]
