# Generated by Django 3.1.3 on 2021-04-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopRestaurant', '0003_restaurant_delivery_preparationtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pickup_preparationtime',
            field=models.SmallIntegerField(default=30, help_text='The time needed to prepare pickup order. Client cannot pickup before this time. Defined in minutes.'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_preparationtime',
            field=models.PositiveSmallIntegerField(default=60, help_text='Time it takes to prepare the order. The client cannot pickup on a time earlier than the defined minutes'),
        ),
    ]
