# Generated by Django 3.1.3 on 2021-04-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopRestaurant', '0004_auto_20210405_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
