# Generated by Django 3.1.3 on 2021-04-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopRestaurant', '0005_auto_20210405_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='bagFee',
            field=models.PositiveSmallIntegerField(default=4, help_text='pose afgift in dkk'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.PositiveSmallIntegerField(default=60, help_text='delivery cost in dkk'),
        ),
    ]
