# Generated by Django 3.1.3 on 2021-05-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopRestaurant', '0006_auto_20210406_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='minimum_orderTotal_for_delivery',
            field=models.PositiveSmallIntegerField(default=400, help_text='How much kr should customer order before local delivery will be offered'),
        ),
    ]
