# Generated by Django 3.1.3 on 2021-05-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshopRestaurant', '0007_restaurant_minimum_ordertotal_for_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='minimum_orderTotal_for_delivery',
            new_name='minimum_order_total_for_delivery',
        ),
    ]
