# Generated by Django 3.1.3 on 2021-05-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopRestaurant', '0008_auto_20210509_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='sessionValidTime',
            field=models.FloatField(default=0.25, help_text='Time length in day that the users session is active'),
        ),
    ]
