# Generated by Django 3.1.3 on 2021-05-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshopRestaurant', '0009_restaurant_sessionvalidtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='sessionValidTime',
            new_name='session_valid_time',
        ),
    ]
