# Generated by Django 3.1.3 on 2021-04-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCatalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergic_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
