# Generated by Django 3.1.3 on 2021-04-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCatalog', '0002_auto_20210404_0607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='products',
            new_name='products_ishere',
        ),
    ]
