# Generated by Django 3.1.3 on 2021-04-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCatalog', '0003_auto_20210404_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='products_ishere',
            new_name='products',
        ),
    ]
