# Generated by Django 3.1.3 on 2021-04-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCatalog', '0004_auto_20210404_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.ImageField(upload_to='productImages'),
        ),
    ]
