# Generated by Django 3.1.3 on 2021-05-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCustomer', '0002_auto_20210506_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deliveryAddressHouseNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='deliveryAddressPostCode',
            field=models.IntegerField(blank=True, default=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='deliveryAddressStreet',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
