# Generated by Django 3.1.3 on 2021-06-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCustomer', '0003_auto_20210509_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='comments',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
