# Generated by Django 3.1.3 on 2021-06-28 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCustomer', '0004_customer_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['fullName']},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='deliveryAddressStreet',
            new_name='deliveryAddress',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='firstname',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='deliveryAddressHouseNumber',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='deliveryAddressPostCode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastname',
        ),
    ]
