# Generated by Django 3.1.3 on 2021-06-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCustomer', '0005_auto_20210628_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30)),
                ('delivery', models.BooleanField(default=False)),
                ('pickup', models.BooleanField(default=False)),
                ('newsletter', models.BooleanField(default=False)),
                ('session_id', models.CharField(max_length=100)),
                ('deliveryAddress', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True, max_length=300)),
                ('orderCreationDateTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['fullName'],
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
