# Generated by Django 3.1.3 on 2021-06-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCustomer', '0006_auto_20210628_1540'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
    ]
