# Generated by Django 3.1.3 on 2021-06-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCustomer', '0007_auto_20210628_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderCreationDateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
