# Generated by Django 3.1.3 on 2021-06-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCustomer', '0009_auto_20210628_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='orderCreationDateTime',
        ),
    ]
