# Generated by Django 3.1.3 on 2021-06-28 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCustomer', '0010_remove_orders_ordercreationdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderCreationDateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
