# Generated by Django 3.1.3 on 2021-06-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCustomer', '0011_orders_ordercreationdatetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
