# Generated by Django 3.1.3 on 2021-06-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCustomer', '0013_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='deliveryTime',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='pickupTime',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
