# Generated by Django 3.1.3 on 2021-06-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCustomer', '0014_auto_20210628_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='pickupTime',
        ),
    ]
