# Generated by Django 3.1.3 on 2021-06-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCustomer', '0015_remove_orders_pickuptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='deliveryTime',
            field=models.CharField(max_length=20),
        ),
    ]
