# Generated by Django 3.1.3 on 2021-06-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopCustomer', '0016_auto_20210628_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='mobile',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
